spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mynix_pos}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false

  flyway:
    enabled: true

textlk:
  api-url: ${TEXTLK_API_URL:https://app.text.lk/api/v3/sms/send}
  api-token: ${TEXTLK_API_TOKEN:6822|R1M0unfzMt0YLcV0Tnt6W4fmnr3nQ56FufyLhBoK445f0189}
  sender-id: ${TEXTLK_SENDER_ID:MYNIX} #Actual API Token related to Sender ID
#sender-id: ${TEXTLK_SENDER_ID:TextLKDemo}  #Temporary Sender ID for testing purposes

mynix:
  public-invoice-base-url: ${MYNIX_PUBLIC_INVOICE_BASE_URL:http://localhost:5173/invoice}
  sms-enabled: ${MYNIX_SMS_ENABLED:true}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${PORT:8080}


