package com.mynix.backend.dto.store;

import com.mynix.backend.model.OnlinePaymentMethod;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

@Data
public class StoreOrderRequest {

    /** Generated by the website per checkout; repeats return the same order. */
    @NotNull
    private UUID requestId;

    @Valid
    @NotEmpty
    @Size(max = 30)
    private List<StoreOrderItem> items;

    @NotNull
    private OnlinePaymentMethod paymentMethod;

    /** Guest checkout: proof the mobile number was verified by SMS code (purpose CHECKOUT). */
    @Size(max = 100)
    private String verificationToken;

    /** Signed-in checkout: the customer's account (the website vouches for the session). */
    private Long customerId;

    /** OnePay transaction id — required for CARD, only after the payment is verified. */
    @Size(max = 100)
    private String paymentReference;

    @NotNull
    @DecimalMin("0.00")
    @DecimalMax("20000.00")
    private BigDecimal deliveryFee;

    @NotBlank
    @Size(max = 150)
    private String customerName;

    /** Sri Lankan mobile: 07XXXXXXXX, 7XXXXXXXX, 947XXXXXXXX or +947XXXXXXXX. */
    @NotBlank
    @Pattern(regexp = "^[+0-9 ()-]{9,20}$")
    private String customerPhone;

    @Email
    @Size(max = 254)
    private String customerEmail;

    @NotBlank
    @Size(max = 200)
    private String addressLine1;

    @Size(max = 200)
    private String addressLine2;

    @NotBlank
    @Size(max = 100)
    private String city;

    @NotBlank
    @Size(max = 100)
    private String district;

    @Size(max = 20)
    private String postalCode;

    @Size(max = 500)
    private String deliveryNotes;
}
